SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Use this SQL script to update an existing JBioWH DB
-- from version 3.1.2 to 3.1.3
-- -----------------------------------------------------

ALTER TABLE `GeneBank` CHANGE COLUMN `Division` `Division` VARCHAR(5) NULL DEFAULT NULL  , ADD COLUMN `Source` VARCHAR(255) NOT NULL  AFTER `Location` , ADD COLUMN `Seq` TEXT NULL DEFAULT NULL  AFTER `Organism` ;

ALTER TABLE `GeneBankCDS` ADD COLUMN `Gene` VARCHAR(45) NULL DEFAULT NULL  AFTER `ProteinId` , ADD COLUMN `Locus_Tag` VARCHAR(45) NULL DEFAULT NULL  AFTER `Gene` 
, ADD UNIQUE INDEX `ProteinGi_UNIQUE` (`ProteinGi` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
