SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Use this SQL script to update an existing JBioWH DB
-- from version 2.1.3 to 3.0.0
-- -----------------------------------------------------

ALTER TABLE `gene_ontology` CHANGE COLUMN `go_id` `go_id` TINYTEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL  , CHANGE COLUMN `term` `term` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL  , CHANGE COLUMN `category` `category` TINYTEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL  ;

ALTER TABLE `UniRefMember` CHANGE COLUMN `TaxId` `TaxId` BIGINT(20) NULL DEFAULT NULL  ;

ALTER TABLE `UniRefMemberTemp` CHANGE COLUMN `TaxId` `TaxId` BIGINT(20) NULL DEFAULT NULL  ;

ALTER TABLE `UniRefMemberTemp1` CHANGE COLUMN `TaxId` `TaxId` BIGINT(20) NULL DEFAULT NULL  ;

ALTER TABLE `UniRefMemberTemp2` CHANGE COLUMN `TaxId` `TaxId` BIGINT(20) NULL DEFAULT NULL  ;

ALTER TABLE `pfamA_ncbi` CHARACTER SET = utf8 , ROW_FORMAT = COMPACT ;

ALTER TABLE `pfamA` CHARACTER SET = utf8 ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
